# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

variables:
  # the name of the service connection that you created above
  serviceConnectionToAzure: sp-ipt-erfa-a
  # the name of your web app here is the same one you used above
  # when you created the web app using the Azure CLI
  appName: my-app-name-ppo


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sp-ipt-erfa-a'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Create a storage account
      az storage account create --name mystorageppo --location westeurope --resource-group ipt-we-erfa-8-rg --sku Standard_LRS
      
      # Create an Azure Functions app
      az functionapp create --resource-group ipt-we-erfa-8-rg --consumption-plan-location westeurope \
      --name my-app-name-ppo --storage-account mystorageppo --runtime java

- task: CopyFiles@2
  displayName: Copy Files
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)/target/azure-functions/
    Contents: '**'
    TargetFolder: $(build.artifactstagingdirectory)   

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)    

- task: AzureFunctionApp@1
  displayName: Azure Function App deploy
  inputs:
    azureSubscription: $(serviceConnectionToAzure)
    appType: functionApp
    appName: $(appName)
    package: $(build.artifactstagingdirectory)/javafunctions